---
- name: Deploy the project
  hosts: web
  roles:
    - role: practical-ansible.nginx-redirect
      nginx_redirect_project_name: cz-polocas-napadu
      nginx_redirect_server_name: polocasnapadu.cz www.polocasnapadu.cz www.polocas-napadu.cz
      nginx_redirect_destination_domain: polocas-napadu.cz
    - role: practical-ansible.nginx-static
      nginx_static_project_name: cz-polocas-napadu
      nginx_static_server_name: polocas-napadu.cz
      nginx_static_project_environment: production
      nginx_static_directory: src/
